# Generated by Django 3.1 on 2020-08-17 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 13, 34, 44, 497104, tzinfo=utc)),
        ),
    ]
